image: node:latest

stages:
  - install
  - lint
  - build
  - deploy

cache:
  paths:
    - node_modules/
    - .yarn-cache/
    - docs/

.base:
  only:
    changes:
      - src/**/*
      - package.json
      - tsconfig.json
      - webpack.config.js
      - .gitlab-ci.yml
      - .prettier*

yarn_install:
  stage: install
  script:
    - yarn install --frozen-lockfile --check-files --cache-folder .yarn-cache

lint:
  stage: lint
  extends: .base
  needs: ['yarn_install']
  script:
    - yarn lint --check

test_build:
  stage: build
  extends: .base
  needs: ['yarn_install']
  script:
    - export NODE_OPTIONS=--openssl-legacy-provider
    - yarn build

pages:
  stage: deploy
  needs: ['yarn_install']
  script:
    - yarn doc
  artifacts:
    paths:
      - docs/
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
