image: node:latest

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/
    - .yarn-cache/
    - docs/

.only:
  only:
    changes:
      - src/**/*
      - package.json
      - tsconfig.json
      - webpack.config.js
      - .gitlab-ci.yml
      - .prettier*

yarn_install:
  stage: build
  extends: .only
  script:
    - yarn install --frozen-lockfile --check-files --cache-folder .yarn-cache

lint:
  stage: build
  needs: ['yarn_install']
  script:
    - yarn lint --check

test_build:
  stage: build
  needs:
    - yarn_install
    - lint
  script:
    - export NODE_OPTIONS=--openssl-legacy-provider
    - yarn build

pages:
  stage: deploy
  script:
    - yarn doc
  artifacts:
    paths:
      - docs/
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
