image: node:latest

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/
    - .yarn-cache/
    - public/

.changes: &changes
  - src/**/*
  - package.json
  - tsconfig.json
  - webpack.config.js
  - .gitlab-ci.yml
  - .prettier*

yarn_install:
  stage: build
  only:
    changes: *changes
  script:
    - yarn install --frozen-lockfile --check-files --cache-folder .yarn-cache

lint:
  stage: build
  only:
    changes: *changes
  needs: ['yarn_install']
  script:
    - yarn lint --check

test_build:
  stage: build
  only:
    changes: *changes
  needs:
    - yarn_install
    - lint
  script:
    - export NODE_OPTIONS=--openssl-legacy-provider
    - yarn build

pages:
  stage: deploy
  script:
    - yarn doc
  artifacts:
    paths: ['public/']
  rules:
    # YAML anchor is used for changes here instead of the extends keyword extends doesn't merge arrays
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      changes: *changes
